# Generated by Django 3.1.2 on 2022-05-07 17:40

import api.helpers
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employeeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=api.helpers.RandomFileName('files/employees/cvs'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.helpers.RandomFileName('images/profile'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'webp', 'svg'])], verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('with cvs', 'with cvs'), ('without cvs', 'without cvs')], max_length=200)),
                ('cvs', models.FileField(blank=True, null=True, upload_to=api.helpers.RandomFileName('files/companies/cvs'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('required_skills', models.TextField(blank=True, null=True)),
                ('required_work_experience', models.TextField(blank=True, null=True)),
                ('required_soft_skills', models.TextField(blank=True, null=True)),
                ('required_languages', models.TextField(blank=True, null=True)),
                ('expire_time', models.DateField()),
                ('status', models.CharField(choices=[('ongoing', 'ongoing'), ('finished', 'finished')], max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
