# Generated by Django 3.1.2 on 2022-05-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220507_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('ongoing', 'ongoing'), ('finished', 'finished')], default='ongoing', max_length=200, null=True),
        ),
    ]
