# Generated by Django 3.1.2 on 2022-05-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_jobapplicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='email',
            field=models.EmailField(default=12, max_length=254),
            preserve_default=False,
        ),
    ]
